# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: "html"
    displayName : "html tag"
    jobs:
      - job: 'junittest'
        displayName: "junt test over here"
        steps:
          - script: echo 'hello world'
          - task: PythonScript@0
            inputs:
              scriptSource: 'inline'
              script: 'print("siva")'
    
